export default [
    {
        name: 'Downey Brand LLP',
        fPercentage: 0.47,
        locallyBased: 'Y',
        totalAttorney: 75,
    },
    {
        name: 'Gordon Rees Scully Mansukhani LLP',
        fPercentage: 0.62,
        locallyBased: 'N',
        totalAttorney: 60,
    },
    {
        name: 'Boutin Jones Inc.',
        fPercentage: 0.27,
        locallyBased: 'Y',
        totalAttorney: 55,
    },
    {
        name: 'Weintraub Tobin',
        fPercentage: 0.38,
        locallyBased: 'Y',
        totalAttorney: 53,
    },
    {
        name: 'Porter Scott',
        fPercentage: 0.43,
        locallyBased: 'Y',
        totalAttorney: 51,
    },
    {
        name: 'Lewis, Brisbois, Bisgaard & Smith LLP',
        fPercentage: 0.33,
        locallyBased: 'N',
        totalAttorney: 43,
    },
    {
        name: 'Buchalter',
        fPercentage: 0.44,
        locallyBased: 'N',
        totalAttorney: 43,
    },
    {
        name: 'Mastagni Holstedt APC',
        fPercentage: 0.21,
        locallyBased: 'Y',
        totalAttorney: 34,
    },
    {
        name: 'Murphy Austin Adams Schoenfeld LLP',
        fPercentage: 0.30,
        locallyBased: 'Y',
        totalAttorney: 33,
    },
    {
        name: 'Kronick Moskovitz Tiedemann & Girard',
        fPercentage: 0.36,
        locallyBased: 'Y',
        totalAttorney: 33,
    },
    {
        name: 'Stoel Rives LLP',
        fPercentage: 0.52,
        locallyBased: 'N',
        totalAttorney: 29,
    },
    {
        name: 'Greenberg Traurig LLP',
        fPercentage: 0.50,
        locallyBased: 'N',
        totalAttorney: 28,
    },
    {
        name: 'Dreyer Babich Buccola Wood Campora LLP',
        fPercentage: 0.22,
        locallyBased: 'Y',
        totalAttorney: 27,
    },
    {
        name: 'Best Best & Krieger LLP',
        fPercentage: 0.50,
        locallyBased: 'N',
        totalAttorney: 26,
    },
    {
        name: 'Lenahan, Slater, Pearse & Majernik LLP',
        fPercentage: 0.50,
        locallyBased: 'Y',
        totalAttorney: 26,
    },
    {
        name: 'Ogletree Deakins',
        fPercentage: 0.52,
        locallyBased: 'N',
        totalAttorney: 25,
    },
    {
        name: 'Gavrilov & Brooks',
        fPercentage: 0.24,
        locallyBased: 'Y',
        totalAttorney: 25,
    },
    {
        name: 'Sims, Lawrence & Broghammer LLP',
        fPercentage: 0.78,
        locallyBased: 'Y',
        totalAttorney: 23,
    },
    {
        name: 'Wilke Fleury LLP',
        fPercentage: 0.23,
        locallyBased: 'Y',
        totalAttorney: 22,
    },
    {
        name: 'Seyfarth Shaw LLP',
        fPercentage: 0.58,
        locallyBased: 'N',
        totalAttorney: 19,
    },
    {
        name: 'Young, Minney & Corr LLP',
        fPercentage: 0.58,
        locallyBased: 'Y',
        totalAttorney: 19,
    },
    {
        name: 'Somach Simmons & Dunn',
        fPercentage: 0.63,
        locallyBased: 'Y',
        totalAttorney: 19,
    },
    {
        name: 'Kennaday Leavitt PC',
        fPercentage: 0.56,
        locallyBased: 'Y',
        totalAttorney: 18,
    },
    {
        name: 'Fisher & Phillips LLP',
        fPercentage: 0.59,
        locallyBased: 'N',
        totalAttorney: 17,
    },
    {
        name: 'Matheny Sears Linkert & Jaime LLP',
        fPercentage: 0.24,
        locallyBased: 'Y',
        totalAttorney: 17,
    },
    {
        name: "Delfino Madden O'Malley Coyle & Koewler LLP",
        fPercentage: 0.53,
        locallyBased: 'Y',
        totalAttorney: 17,
    },
    {
        name: 'Littler',
        fPercentage: 0.63,
        locallyBased: 'N',
        totalAttorney: 16,
    },
    {
        name: 'Van Dermyden Makus Law Corp.',
        fPercentage: 0.60,
        locallyBased: 'Y',
        totalAttorney: 15,
    },
    {
        name: 'Remy Moose Manley LLP',
        fPercentage: 0.67,
        locallyBased: 'Y',
        totalAttorney: 15,
    },
    {
        name: 'White Brenner LLP',
        fPercentage: 0.67,
        locallyBased: 'Y',
        totalAttorney: 15,
    },
    {
        name: 'BPE Law Group',
        fPercentage: 0.46,
        locallyBased: 'Y',
        totalAttorney: 13,
    },
    {
        name: 'Ellison Schneider Harris & Donlan LLP',
        fPercentage: 0.38,
        locallyBased: 'Y',
        totalAttorney: 13,
    },
    {
        name: 'Fennemore WKBKY',
        fPercentage: 0.42,
        locallyBased: 'N',
        totalAttorney: 12,
    },
    {
        name: 'La Follette, Johnson, DeHass, Fesler & Ames',
        fPercentage: 0.42,
        locallyBased: 'N',
        totalAttorney: 12,
    },
    {
        name: 'Arnold Law Firm',
        fPercentage: 0.17,
        locallyBased: 'Y',
        totalAttorney: 12,
    },
    {
        name: 'Daponde Simpson Rowe PC',
        fPercentage: 0.75,
        locallyBased: 'Y',
        totalAttorney: 12,
    },
    {
        name: 'Sloan Sakai Yeung & Wong LLP',
        fPercentage: 0.64,
        locallyBased: 'Y',
        totalAttorney: 11,
    },
    {
        name: 'Gurnee Mason Rushford Bonotto & Forestiere LLP',
        fPercentage: 0.09,
        locallyBased: 'Y',
        totalAttorney: 11,
    },
    {
        name: 'Powers Miller Attorneys at Law',
        fPercentage: 0.27,
        locallyBased: 'Y',
        totalAttorney: 11,
    },
    {
        name: 'Hefner Law',
        fPercentage: 0.09,
        locallyBased: 'Y',
        totalAttorney: 11,
    },
    {
        name: 'Medina McKelvey LLP',
        fPercentage: 0.60,
        locallyBased: 'Y',
        totalAttorney: 10,
    },
    {
        name: 'Plante Huguenin Lebovic Kahn LLP',
        fPercentage: 0.22,
        locallyBased: 'N',
        totalAttorney: 9,
    },
    {
        name: 'Meissner Joseph Ruggles Inc.',
        fPercentage: 0.56,
        locallyBased: 'Y',
        totalAttorney: 9,
    },
    {
        name: 'Shaw Law Group',
        fPercentage: 0.78,
        locallyBased: 'Y',
        totalAttorney: 9,
    },
    {
        name: 'Smith, McDowell & Powell, A Law Corp.',
        fPercentage: 0.22,
        locallyBased: 'Y',
        totalAttorney: 9,
    },
    {
        name: 'Young, Cohen & Durrett LLP',
        fPercentage: 0.22,
        locallyBased: 'Y',
        totalAttorney: 9,
    },
    {
        name: 'Cole Huber LLP',
        fPercentage: 0.25,
        locallyBased: 'Y',
        totalAttorney: 8,
    },
    {
        name: 'LeVangie Law Group',
        fPercentage: 0.29,
        locallyBased: 'Y',
        totalAttorney: 7,
    },
    {
        name: 'Muro & Lampe Inc.',
        fPercentage: 0.17,
        locallyBased: 'Y',
        totalAttorney: 6,
    },
    {
        name: 'Duggan McHugh Law Corp.',
        fPercentage: 0.83,
        locallyBased: 'Y',
        totalAttorney: 6,
    },
    {
        name: 'Purcell Stowell PC',
        fPercentage: 0.83,
        locallyBased: 'Y',
        totalAttorney: 6,
    },
    {
        name: 'Messing Adam & Jasmine',
        fPercentage: 0.40,
        locallyBased: 'Y',
        totalAttorney: 5,
    },
    {
        name: 'Ellis Investigations Law Corporation',
        fPercentage: 0.80,
        locallyBased: 'Y',
        totalAttorney: 5,
    },
    {
        name: 'Felderstein Fitzgerald Willoughby Pascuzzi & Rios LLP',
        fPercentage: 0.20,
        locallyBased: 'Y',
        totalAttorney: 5,
    },
    {
        name: 'Rojas & Nickelson Family Law Inc.',
        fPercentage: 1.00,
        locallyBased: 'Y',
        totalAttorney: 4,
    },
    {
        name: 'Dudensing Law',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 4,
    },
    {
        name: "O'Connor Thompson McDonough Klotsche LLP",
        fPercentage: 0.50,
        locallyBased: 'Y',
        totalAttorney: 4,
    },
    {
        name: 'The Law Offices of Dale R. Gomes',
        fPercentage: 0.33,
        locallyBased: 'N',
        totalAttorney: 3,
    },
    {
        name: 'Frank Penney Injury Lawyers PC',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 3,
    },
    {
        name: 'Frank Law Group P.C.',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 3,
    },
    {
        name: 'Lazzarini, Whiteford & Young, LLP',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 2,
    },
    {
        name: 'Law Offices of Sid M. Rosenberg Inc.',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 2,
    },
    {
        name: 'Soluri Meserve',
        fPercentage: 0.50,
        locallyBased: 'Y',
        totalAttorney: 2,
    },
    {
        name: 'United Law Center PLC',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 2,
    },
    {
        name: 'Harvest Law',
        fPercentage: 1.00,
        locallyBased: 'Y',
        totalAttorney: 1,
    },
    {
        name: 'Hughey Law, a Professional Corp.',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 1,
    },
    {
        name: 'Lowenthal APC',
        fPercentage: 0.00,
        locallyBased: 'Y',
        totalAttorney: 1,
    },
    {
        name: 'Candice Fields Law PC',
        fPercentage: 1.00,
        locallyBased: 'Y',
        totalAttorney: 1,
    },
]